export const recentDogData = [
  {
    id: 1,
    photo: '',
    location: '서울',
    name: '바둑이1',
    breed: '푸들',
    birthDate: '2020-01-01',
    gender: '암컷',
    breederName: '홍길동',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 2,
    photo: '',
    location: '부산',
    name: '바둑이2',
    breed: '포메라니안',
    birthDate: '2020-02-01',
    gender: '수컷',
    breederName: '김철수',
    waitlistCount: 3,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 3,
    photo: '',
    location: '대구',
    name: '바둑이3',
    breed: '시츄',
    birthDate: '2020-03-01',
    gender: '암컷',
    breederName: '이영희',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 4,
    photo: '',
    location: '인천',
    name: '바둑이4',
    breed: '말티즈',
    birthDate: '2020-04-01',
    gender: '수컷',
    breederName: '박영수',
    waitlistCount: 1,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 5,
    photo: '',
    location: '광주',
    name: '바둑이5',
    breed: '치와와',
    birthDate: '2020-05-01',
    gender: '암컷',
    breederName: '최정호',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 6,
    photo: '',
    location: '대전',
    name: '바둑이6',
    breed: '요크셔 테리어',
    birthDate: '2020-06-01',
    gender: '수컷',
    breederName: '정민호',
    waitlistCount: 6,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 7,
    photo: '',
    location: '울산',
    name: '바둑이7',
    breed: '비숑 프리제',
    birthDate: '2020-07-01',
    gender: '암컷',
    breederName: '강소영',
    waitlistCount: 2,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 8,
    photo: '',
    location: '경기',
    name: '바둑이8',
    breed: '불독',
    birthDate: '2020-08-01',
    gender: '수컷',
    breederName: '윤재민',
    waitlistCount: 7,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 9,
    photo: '',
    location: '강원',
    name: '바둑이9',
    breed: '달마시안',
    birthDate: '2020-09-01',
    gender: '암컷',
    breederName: '한지민',
    waitlistCount: 9,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 10,
    photo: '',
    location: '충북',
    name: '바둑이10',
    breed: '골든 리트리버',
    birthDate: '2020-10-01',
    gender: '수컷',
    breederName: '백진우',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 11,
    photo: '',
    location: '충남',
    name: '바둑이11',
    breed: '래브라도 리트리버',
    birthDate: '2020-11-01',
    gender: '암컷',
    breederName: '양수진',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 12,
    photo: '',
    location: '전북',
    name: '바둑이12',
    breed: '도베르만',
    birthDate: '2020-12-01',
    gender: '수컷',
    breederName: '우정민',
    waitlistCount: 15,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 13,
    photo: '',
    location: '전남',
    name: '바둑이13',
    breed: '그레이하운드',
    birthDate: '2021-01-01',
    gender: '암컷',
    breederName: '박은수',
    waitlistCount: 3,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 14,
    photo: '',
    location: '경북',
    name: '바둑이14',
    breed: '보더 콜리',
    birthDate: '2021-02-01',
    gender: '수컷',
    breederName: '한정우',
    waitlistCount: 7,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 15,
    photo: '',
    location: '경남',
    name: '바둑이15',
    breed: '사모예드',
    birthDate: '2021-03-01',
    gender: '암컷',
    breederName: '이선영',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 16,
    photo: '',
    location: '제주',
    name: '바둑이16',
    breed: '시베리안 허스키',
    birthDate: '2021-04-01',
    gender: '수컷',
    breederName: '김한나',
    waitlistCount: 4,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 17,
    photo: '',
    location: '서울',
    name: '바둑이17',
    breed: '슈나우저',
    birthDate: '2021-05-01',
    gender: '암컷',
    breederName: '박진수',
    waitlistCount: 6,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 18,
    photo: '',
    location: '부산',
    name: '바둑이18',
    breed: '웰시 코기',
    birthDate: '2021-06-01',
    gender: '수컷',
    breederName: '강지수',
    waitlistCount: 2,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 19,
    photo: '',
    location: '대구',
    name: '바둑이19',
    breed: '비글',
    birthDate: '2021-07-01',
    gender: '암컷',
    breederName: '홍지민',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 20,
    photo: '',
    location: '인천',
    name: '바둑이20',
    breed: '차우 차우',
    birthDate: '2021-08-01',
    gender: '수컷',
    breederName: '윤지훈',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 21,
    photo: '',
    location: '광주',
    name: '바둑이21',
    breed: '핏불 테리어',
    birthDate: '2021-09-01',
    gender: '암컷',
    breederName: '고은성',
    waitlistCount: 8,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 22,
    photo: '',
    location: '대전',
    name: '바둑이22',
    breed: '로트와일러',
    birthDate: '2021-10-01',
    gender: '수컷',
    breederName: '이정민',
    waitlistCount: 1,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 23,
    photo: '',
    location: '울산',
    name: '바둑이23',
    breed: '그레이트 데인',
    birthDate: '2021-11-01',
    gender: '암컷',
    breederName: '송지호',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 24,
    photo: '',
    location: '경기',
    name: '바둑이24',
    breed: '닥스훈트',
    birthDate: '2021-12-01',
    gender: '수컷',
    breederName: '권지수',
    waitlistCount: 6,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 25,
    photo: '',
    location: '강원',
    name: '바둑이25',
    breed: '시바 이누',
    birthDate: '2022-01-01',
    gender: '암컷',
    breederName: '백준호',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 26,
    photo: '',
    location: '충북',
    name: '바둑이26',
    breed: '사모예드',
    birthDate: '2022-02-01',
    gender: '수컷',
    breederName: '김민정',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 27,
    photo: '',
    location: '충남',
    name: '바둑이27',
    breed: '보더 콜리',
    birthDate: '2022-03-01',
    gender: '암컷',
    breederName: '안지수',
    waitlistCount: 12,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 28,
    photo: '',
    location: '전북',
    name: '바둑이28',
    breed: '달마시안',
    birthDate: '2022-04-01',
    gender: '수컷',
    breederName: '정하영',
    waitlistCount: 15,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 29,
    photo: '',
    location: '전남',
    name: '바둑이29',
    breed: '비숑 프리제',
    birthDate: '2022-05-01',
    gender: '암컷',
    breederName: '김유정',
    waitlistCount: 3,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 30,
    photo: '',
    location: '경북',
    name: '바둑이30',
    breed: '차우 차우',
    birthDate: '2022-06-01',
    gender: '수컷',
    breederName: '박수현',
    waitlistCount: 7,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 31,
    photo: '',
    location: '경남',
    name: '바둑이31',
    breed: '포메라니안',
    birthDate: '2022-07-01',
    gender: '암컷',
    breederName: '최유진',
    waitlistCount: 1,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 32,
    photo: '',
    location: '제주',
    name: '바둑이32',
    breed: '래브라도 리트리버',
    birthDate: '2022-08-01',
    gender: '수컷',
    breederName: '이준호',
    waitlistCount: 4,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
];

export const recentBreederData = [
  {
    id: 1,
    photo: '',
    name: '홍길동',
    location: '서울 강서구',
    breederExperience: '비글, 골든리트리버 전문',
  },
  {
    id: 2,
    photo: '',
    name: '김철수',
    location: '부산',
    breederExperience: '3년',
  },
  {
    id: 3,
    photo: '',
    name: '이영희',
    location: '대구',
    breederExperience: '2년',
  },
  {
    id: 4,
    photo: '',
    name: '최수민',
    location: '인천',
    breederExperience: '4년',
  },
  {
    id: 5,
    photo: '',
    name: '박준영',
    location: '대전',
    breederExperience: '6년',
  },
  {
    id: 6,
    photo: '',
    name: '김정훈',
    location: '광주',
    breederExperience: '1년',
  },
  {
    id: 7,
    photo: '',
    name: '이영수',
    location: '울산',
    breederExperience: '7년',
  },
  {
    id: 8,
    photo: '',
    name: '한지수',
    location: '수원',
    breederExperience: '2년',
  },
  {
    id: 9,
    photo: '',
    name: '장동건',
    location: '창원',
    breederExperience: '5년',
  },
  {
    id: 10,
    photo: '',
    name: '이수현',
    location: '청주',
    breederExperience: '9년',
  },
];
