export const recentDogData = [
  {
    id: 1,
    photo: '',
    location: '서울',
    name: '바둑이',
    breed: '푸들',
    birthDate: '2020-01-01',
    gender: '암컷',
    breederName: '홍길동',
    waitlistCount: 5,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 2,
    photo: '',
    location: '부산',
    name: '멍멍이',
    breed: '불독',
    birthDate: '2019-05-12',
    gender: '수컷',
    breederName: '김철수',
    waitlistCount: 3,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 3,
    photo: '',
    location: '대구',
    name: '쫑이',
    breed: '시바견',
    birthDate: '2018-11-23',
    gender: '암컷',
    breederName: '이영희',
    waitlistCount: 2,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 4,
    photo: '',
    location: '인천',
    name: '코코',
    breed: '코카스파니엘',
    birthDate: '2021-02-14',
    gender: '암컷',
    breederName: '최수민',
    waitlistCount: 4,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 5,
    photo: '',
    location: '대전',
    name: '초코',
    breed: '치와와',
    birthDate: '2020-08-19',
    gender: '수컷',
    breederName: '박준영',
    waitlistCount: 6,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 6,
    photo: '',
    location: '광주',
    name: '누리',
    breed: '진돗개',
    birthDate: '2019-04-11',
    gender: '암컷',
    breederName: '김정훈',
    waitlistCount: 1,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 7,
    photo: '',
    location: '울산',
    name: '왕자',
    breed: '골든리트리버',
    birthDate: '2018-07-22',
    gender: '수컷',
    breederName: '이영수',
    waitlistCount: 8,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 8,
    photo: '',
    location: '수원',
    name: '미미',
    breed: '포메라니안',
    birthDate: '2021-01-15',
    gender: '암컷',
    breederName: '한지수',
    waitlistCount: 0,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 9,
    photo: '',
    location: '창원',
    name: '뚜리',
    breed: '말티즈',
    birthDate: '2017-03-05',
    gender: '수컷',
    breederName: '장동건',
    waitlistCount: 7,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
  {
    id: 10,
    photo: '',
    location: '청주',
    name: '사랑이',
    breed: '비숑프리제',
    birthDate: '2020-09-10',
    gender: '암컷',
    breederName: '이수현',
    waitlistCount: 9,
    isBookmarked: false,
    setIsBookmarked: () => {},
  },
];

export const recentBreederData = [
  {
    id: 1,
    photo: '',
    name: '홍길동',
    location: '서울 강서구',
    breederExperience: '비글, 골든리트리버 전문',
  },
  {
    id: 2,
    photo: '',
    name: '김철수',
    location: '부산',
    breederExperience: '3년',
  },
  {
    id: 3,
    photo: '',
    name: '이영희',
    location: '대구',
    breederExperience: '2년',
  },
  {
    id: 4,
    photo: '',
    name: '최수민',
    location: '인천',
    breederExperience: '4년',
  },
  {
    id: 5,
    photo: '',
    name: '박준영',
    location: '대전',
    breederExperience: '6년',
  },
  {
    id: 6,
    photo: '',
    name: '김정훈',
    location: '광주',
    breederExperience: '1년',
  },
  {
    id: 7,
    photo: '',
    name: '이영수',
    location: '울산',
    breederExperience: '7년',
  },
  {
    id: 8,
    photo: '',
    name: '한지수',
    location: '수원',
    breederExperience: '2년',
  },
  {
    id: 9,
    photo: '',
    name: '장동건',
    location: '창원',
    breederExperience: '5년',
  },
  {
    id: 10,
    photo: '',
    name: '이수현',
    location: '청주',
    breederExperience: '9년',
  },
];
