/* eslint-disable import/prefer-default-export */
export const waitingDogData = [
  {
    id: 1,
    photo: '',
    location: '서울 강서구',
    name: '행복이',
    breed: '비글',
    birthDate: '2023-02-14',
    gender: '암컷',
    breederName: '해피켄넬',
    waitlistCount: 4,
  },
  {
    id: 2,
    photo: '',
    location: '서울 강서구',
    name: '사랑이',
    breed: '포메라니안',
    birthDate: '2023-03-01',
    gender: '암컷',
    breederName: '러브펫',
    waitlistCount: 3,
  },
  {
    id: 3,
    photo: '',
    location: '서울 강서구',
    name: '복덩이',
    breed: '골든 리트리버',
    birthDate: '2023-01-20',
    gender: '수컷',
    breederName: '송파켄넬',
    waitlistCount: 5,
  },
  {
    id: 4,
    photo: '',
    location: '서울 강서구',
    name: '행운이',
    breed: '시추',
    birthDate: '2022-12-25',
    gender: '암컷',
    breederName: '행운펫',
    waitlistCount: 2,
  },
  {
    id: 5,
    photo: '',
    location: '서울 강서구',
    name: '왕자',
    breed: '프렌치 불독',
    birthDate: '2023-05-10',
    gender: '수컷',
    breederName: '강동펫샵',
    waitlistCount: 6,
  },
  {
    id: 6,
    photo: '',
    location: '서울 강서구',
    name: '별이',
    breed: '치와와',
    birthDate: '2023-04-14',
    gender: '암컷',
    breederName: '스타켄넬',
    waitlistCount: 4,
  },
  {
    id: 7,
    photo: '',
    location: '서울 강서구',
    name: '해피',
    breed: '코카 스파니엘',
    birthDate: '2023-02-28',
    gender: '수컷',
    breederName: '해피독스',
    waitlistCount: 1,
  },
  {
    id: 8,
    photo: '',
    location: '서울 강서구',
    name: '초코',
    breed: '닥스훈트',
    birthDate: '2023-03-15',
    gender: '암컷',
    breederName: '초코펫샵',
    waitlistCount: 8,
  },
  {
    id: 9,
    photo: '',
    location: '서울 강서구',
    name: '미소',
    breed: '시베리안 허스키',
    birthDate: '2023-02-10',
    gender: '암컷',
    breederName: '허스키랜드',
    waitlistCount: 7,
  },
  {
    id: 10,
    photo: '',
    location: '서울 강서구',
    name: '호두',
    breed: '보더 콜리',
    birthDate: '2023-01-05',
    gender: '수컷',
    breederName: '동작펫',
    waitlistCount: 3,
  },
];
