export const 전체DogCard = [
  {
    photo: '',
    location: '서울',
    name: '바둑이',
    breed: '포메라니안',
    birthDate: '2020-01-01',
    gender: '수컷',
    breederName: '김철수',
    waitlistCount: 5,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '부산',
    name: '쫑이',
    breed: '푸들',
    birthDate: '2019-05-03',
    gender: '암컷',
    breederName: '이영희',
    waitlistCount: 2,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '대구',
    name: '멍멍이',
    breed: '말티즈',
    birthDate: '2018-07-11',
    gender: '수컷',
    breederName: '박민수',
    waitlistCount: 7,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '인천',
    name: '냥이',
    breed: '러시안 블루',
    birthDate: '2017-12-24',
    gender: '암컷',
    breederName: '최지우',
    waitlistCount: 3,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '광주',
    name: '코코',
    breed: '비숑 프리제',
    birthDate: '2021-03-15',
    gender: '수컷',
    breederName: '정성훈',
    waitlistCount: 4,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '대전',
    name: '하루',
    breed: '치와와',
    birthDate: '2022-10-10',
    gender: '암컷',
    breederName: '박지성',
    waitlistCount: 0,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '울산',
    name: '보리',
    breed: '요크셔 테리어',
    birthDate: '2020-08-20',
    gender: '수컷',
    breederName: '김하늘',
    waitlistCount: 1,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '수원',
    name: '사랑이',
    breed: '골든 리트리버',
    birthDate: '2019-02-05',
    gender: '암컷',
    breederName: '홍길동',
    waitlistCount: 8,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '성남',
    name: '몽이',
    breed: '보더 콜리',
    birthDate: '2016-04-25',
    gender: '수컷',
    breederName: '박찬호',
    waitlistCount: 10,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '청주',
    name: '초코',
    breed: '닥스훈트',
    birthDate: '2018-09-14',
    gender: '암컷',
    breederName: '이순신',
    waitlistCount: 9,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '전주',
    name: '나비',
    breed: '페르시안',
    birthDate: '2017-06-30',
    gender: '수컷',
    breederName: '안중근',
    waitlistCount: 11,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '제주',
    name: '모찌',
    breed: '프렌치 불독',
    birthDate: '2015-11-19',
    gender: '암컷',
    breederName: '유관순',
    waitlistCount: 4,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '강릉',
    name: '까미',
    breed: '비글',
    birthDate: '2021-01-01',
    gender: '수컷',
    breederName: '김구',
    waitlistCount: 7,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '포항',
    name: '보라',
    breed: '사모예드',
    birthDate: '2022-12-31',
    gender: '암컷',
    breederName: '윤봉길',
    waitlistCount: 5,
    isBookmarked: false,
  },
  {
    photo: '',
    location: '서울',
    name: '마루',
    breed: '달마티안',
    birthDate: '2018-03-03',
    gender: '수컷',
    breederName: '김좌진',
    waitlistCount: 6,
    isBookmarked: false,
  },
];

export const 전체BreederCard = [
  {
    photo: '',
    location: '서울',
    name: '김철수',
    breederExperience: '5년',
    numberOfCertifications: 3,
    waitingDogs: 5,
    waitlistCount: 2,
    rating: 4.5,
    reviewCount: 10,
  },
  {
    photo: '',
    location: '부산',
    name: '이영희',
    breederExperience: '10년',
    numberOfCertifications: 5,
    waitingDogs: 8,
    waitlistCount: 4,
    rating: 4.8,
    reviewCount: 20,
  },
  {
    photo: '',
    location: '대구',
    name: '박민수',
    breederExperience: '3년',
    numberOfCertifications: 2,
    waitingDogs: 3,
    waitlistCount: 1,
    rating: 4.2,
    reviewCount: 5,
  },
  {
    photo: '',
    location: '인천',
    name: '최지영',
    breederExperience: '7년',
    numberOfCertifications: 4,
    waitingDogs: 6,
    waitlistCount: 3,
    rating: 4.6,
    reviewCount: 15,
  },
  {
    photo: '',
    location: '광주',
    name: '김은정',
    breederExperience: '6년',
    numberOfCertifications: 3,
    waitingDogs: 7,
    waitlistCount: 2,
    rating: 4.7,
    reviewCount: 12,
  },
  {
    photo: '',
    location: '대전',
    name: '이승현',
    breederExperience: '4년',
    numberOfCertifications: 2,
    waitingDogs: 4,
    waitlistCount: 1,
    rating: 4.4,
    reviewCount: 8,
  },
  {
    photo: '',
    location: '울산',
    name: '한지민',
    breederExperience: '8년',
    numberOfCertifications: 5,
    waitingDogs: 9,
    waitlistCount: 5,
    rating: 4.9,
    reviewCount: 25,
  },
  {
    photo: '',
    location: '경기',
    name: '박서준',
    breederExperience: '2년',
    numberOfCertifications: 1,
    waitingDogs: 2,
    waitlistCount: 1,
    rating: 4.1,
    reviewCount: 3,
  },
  {
    photo: '',
    location: '강원',
    name: '최예진',
    breederExperience: '9년',
    numberOfCertifications: 4,
    waitingDogs: 7,
    waitlistCount: 3,
    rating: 4.7,
    reviewCount: 18,
  },
  {
    photo: '',
    location: '충북',
    name: '김지훈',
    breederExperience: '1년',
    numberOfCertifications: 1,
    waitingDogs: 1,
    waitlistCount: 0,
    rating: 3.9,
    reviewCount: 2,
  },
  {
    photo: '',
    location: '충남',
    name: '이수정',
    breederExperience: '11년',
    numberOfCertifications: 6,
    waitingDogs: 10,
    waitlistCount: 6,
    rating: 4.8,
    reviewCount: 30,
  },
  {
    photo: '',
    location: '경북',
    name: '김태영',
    breederExperience: '3년',
    numberOfCertifications: 2,
    waitingDogs: 3,
    waitlistCount: 1,
    rating: 4.3,
    reviewCount: 6,
  },
  {
    photo: '',
    location: '전북',
    name: '박진우',
    breederExperience: '5년',
    numberOfCertifications: 3,
    waitingDogs: 5,
    waitlistCount: 2,
    rating: 4.5,
    reviewCount: 10,
  },
  {
    photo: '',
    location: '전남',
    name: '서지수',
    breederExperience: '4년',
    numberOfCertifications: 2,
    waitingDogs: 4,
    waitlistCount: 1,
    rating: 4.4,
    reviewCount: 8,
  },
  {
    photo: '',
    location: '제주',
    name: '최현우',
    breederExperience: '2년',
    numberOfCertifications: 1,
    waitingDogs: 2,
    waitlistCount: 1,
    rating: 4.1,
    reviewCount: 3,
  },
];

export const cities = [
  '서울',
  '세종',
  '강원',
  '인천',
  '경기',
  '충북',
  '충남',
  '경북',
  '대전',
  '대구',
  '전북',
  '경남',
  '울산',
  '광주',
  '부산',
  '전남',
  '제주',
];

export const animalBreeds = {
  dog: [
    '골든 리트리버',
    '닥스훈트',
    '도베르만 핀셔',
    '래브라도 레트리버',
    '말티즈',
    '말티푸',
    '미니어처 슈나우저',
    '미니어처 핀셔',
    '베들링턴 테리어',
    '보더콜리',
    '비글',
    '비숑프리제',
    '사모예드',
    '시바이누',
    '시베리아허스키',
    '시추',
    '알래스칸 맬러뮤트',
    '요크셔테리어',
    '웰시코기',
    '이탈리안 그레이 하운드',
    '재페니스 스피츠',
    '잭 러셀 테리어',
    '저먼 셰퍼드',
    '차우차우',
    '치와와',
    '파피용',
    '퍼그',
    '포메라니안',
    '푸들',
    '프렌치불독',
    '기타',
  ],
  cat: [
    '노르웨이 숲',
    '데본 렉스',
    '돈스코이',
    '랙돌',
    '러시안 블루',
    '맹크스',
    '먼치킨',
    '메인 쿤',
    '민스킨',
    '벵갈',
    '봄베이',
    '브리티시 숏헤어',
    '사바나',
    '샴',
    '소말리',
    '소코케',
    '스코티쉬 폴드',
    '스핑크스',
    '아메리칸 밥테일',
    '아메리칸 숏헤어',
    '아메리칸 컬',
    '아비니시안',
    '엑조틱 숏헤어',
    '오리엔탈',
    '카오 마니',
    '코리안 숏헤어',
    '터키쉬 앙고라',
    '페르시안',
    '기타',
  ],
  entire: [],
};
animalBreeds.entire = [...animalBreeds.dog, ...animalBreeds.cat];
